name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        run: curl -X POST https://siddharthsaraf.pythonanywhere.com/deploy-hook-${{ secrets.WEBHOOK_SECRET }}/